#! /bin/sh

source ~/.zshrc

#pgrep -x sxhkd > /dev/null || sxhkd 2>&1 >> ~/.log/sxhkd.log &
# Started with systemctl

#start polybar
/home/dj1n/.config/polybar/launch.sh

bspc monitor DVI-D-0 -d Accueil Code-1 Code-2 Lutris Steam # Gauche
bspc monitor DVI-I-0 -d Streaming Gaming Docs YouTube Music # Droite

bspc config border_width			2
bspc config normal_border_color		"#6212ff"
bspc config focused_border_color	"#00ffbe"
bspc config window_gap				12

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a vivaldi desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
